### ISSUE TITLE
Adding license

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/awesome-portfolio-template#12]
Our repository doesn't have any licenses for now. Need to add a proper one.

**Comment by NovusEdge** [comment]
If you wish to add an OSS license, I would suggest checking out: https://choosealicense.com/

**Comment by niloysikdar** [comment]
Thanks, @NovusEdge , do you want to work on the issue?

**Comment by NovusEdge** [comment]
Sure, I can work on it, just let me know of the details of what I have to do

**Comment by niloysikdar** [comment]
Okay @NovusEdge , I think we can go with the GNU GPLv3 license.
