### ISSUE TITLE
Adding blogs

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/awesome-portfolio-template#14]
Need to add blog cards in the blog section.

**Comment by harshita2216** [comment]
I'd like to work on this issue.

**Comment by niloysikdar** [comment]
Sorry @harshita2216 , but you have some other work to finish first

**Comment by harshita2216** [comment]
> Sorry @harshita2216 , but you have some other work to finish first

I haven't been assigned any issue yet. @niloysikdar

**Comment by niloysikdar** [comment]
Currently, We don't need to work on this issue. Will implement it later if needed.

**Comment by harshita2216** [comment]
@niloysikdar This can be closed if it's not needed at the moment. Thanks anyway.

**Comment by niloysikdar** [comment]
Right @harshita2216 , thanks :-)
