### ISSUE TITLE
Adding a education section

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/awesome-portfolio-template#18]
Need to add an education section where users can showcase their education details.

**Comment by danielbettech** [comment]
Just add a proposal for the Education Section.
Let me know your comments.

[Pull Request 44](https://github.com/niloysikdar/awesome-portfolio-template/pull/44)

**Comment by niloysikdar** [comment]
Yeah merged it, awesome @danielbettech . Not closing this issue for now as we need some more responsiveness for small screen views.

**Comment by danielbettech** [comment]
Great @niloysikdar.
