### ISSUE TITLE
Social Icons

### ISSUE THREAD

**Issue by niloysikdar** [niloysikdar/awesome-portfolio-template#19]
Need to add a section to add social icons like LinkedIn, GitHub, Medium, Kaggle, Instagram, etc.

**Comment by stevenks17** [comment]
Hello,

Can you elaborate on this some more do you mean a container for icons or you need to import the icons for use?

**Comment by niloysikdar** [comment]
Hello @stevenks17 , We need to add some icons for different handles where the users can attach the relevant links.
Like this : 
![Capture](https://user-images.githubusercontent.com/58071992/115279062-d908d100-a163-11eb-959e-6371cf0b5487.PNG)
