### ISSUE TITLE
Preloader needed for the site

### ISSUE THREAD

**Issue by imniladri** [niloysikdar/awesome-portfolio-template#45]
**Is your feature request related to a problem? Please describe.**
Currently our site doesn't had a preloader!

**Describe the solution you'd like**
I want to add a custom preloader.

**Describe alternatives you've considered**

**Additional context**

**Comment by niloysikdar** [comment]
Awesome @imniladri , you can work on this.

**Comment by imniladri** [comment]
Custom loader added in the site!
Hope you will like it!
